document.writeln("   <ul id=\"navigation\"> ");
document.writeln("     <li><a target=\"_parent\"  class=\"fly\" href=\"#url\"><b>Menu</b></a> ");
document.writeln("       <ul id=\"flyout2\"> ");
document.writeln("         <li><a target=\"_parent\"  href=\"../about.html\">About US</a></li> ");
document.writeln("         <li><a target=\"_parent\"  class=\"fly\" href=\"#url\">Nice Ideas</a> ");
document.writeln("           <ul> ");
document.writeln("             <li><a target=\"_parent\"   href=\"mustread.html\">Five of my Favorites</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"quotes.html\">Quotes for Life</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"installlove.html\">Install Love</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"cognitivebt.html\">Cognitive Behavioral Writings</a></li> ");
document.writeln("           </ul> ");
document.writeln("         </li> ");
document.writeln("         <li ><a target=\"_parent\"  class=\"fly\" href=\"#url\">Pithy</a> ");
document.writeln("           <ul> ");
document.writeln("             <li><a target=\"_parent\"   href=\"TinyPoems.html\">Little Poems</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"Lying.html\">Lying</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"Proverbs.htm\">Proverbs</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"Leadership.htm\">Leadership</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"Tact.htm\">Tact</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"wit.html\">Wit</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"Proverbsforourtime.html\">Proverbs for our time</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"Definitions.html\">Definitions</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"WorkDefinitions.html\">The Workplace</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"oneliners.html\">Short Stuff</a></li> ");
document.writeln("           </ul> ");
document.writeln("         </li> ");
document.writeln("         <li><a target=\"_parent\"  class=\"fly\" href=\"#url\">Great Thinkers</a> ");
document.writeln("           <ul> ");
document.writeln("             <li><a target=\"_parent\"   href=\"ThomasJefferson.htm\">Thomas Jefferson</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"MahatmaGandhi.htm\">Mahatma Ghandi</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"RalphWaldoEmerson.htm\">Ralph Waldo Emerson</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"AlbertEinstein.htm\">Albert Einstein</a></li> ");
document.writeln("           </ul> ");
document.writeln("         </li> ");
document.writeln("         <li ><a target=\"_parent\"  class=\"fly\" href=\"#url\">Comic Thinkers</a> ");
document.writeln("           <ul> ");
document.writeln("             <li><a target=\"_parent\"   href=\"GROUCHOMARX.htm\">Groucho Marx</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"GeorgeCarlin.html\">George Carlin</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"MTWAIN.html\">Mark Twain</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"DaveBarry.html\">Dave Barry</a></li> ");
document.writeln("           </ul> ");
document.writeln("         </li> ");
document.writeln("         <li><a target=\"_parent\"  class=\"fly\" href=\"#url\">Fun</a> ");
document.writeln("           <ul> ");
document.writeln("             <li><a target=\"_parent\"   href=\"bostondirections.html\">Boston directions</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"writtenword.html\">Humor</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"france.html\">France</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"ContempoaryLatinPhrases.html\">Contemporary Latin Phrases</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"PoliticalGems.htm\">Politics</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"OldPeopleStories.html\">Old People Stories</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"Religion.html\">Religion</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"SmartHouse.html\">The Home of the Future</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"SecurityLevels.html\">Threat Levels</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"../fun/WavDownloads.htm\" >Wav Clips</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"../fun/fakesearch.html\" >Ask Anne and Gary</a></li> ");
document.writeln("            </ul> ");
document.writeln("         </li> ");
document.writeln(" <!-- keep the last 2 short, a long number of entries go off the screen at 1024 x 768 screen --> ");
document.writeln("         <li ><a target=\"_parent\"  class=\"fly\" href=\"#url\">For the Easily Amused</a> ");
document.writeln("           <ul> ");
document.writeln("             <li><a target=\"_parent\"   href=\"../fun/gjfun.html\" >Gif Animations</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"../XXSoftwareTools/Moves.html\" >Javascript Animation</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"../fun/contest.html\" >Enter Contest</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"../fun/bunny.html\" >A few silly rabbits</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"../KandinskyCanvas.html\" >A Kandinsky in Canvas</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"../mysolvemedia.php\" >Are you human?</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"GaryThoughts.html\">Gary</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"../Error.html\">Do Not Click Here &not; &nbsp;!</a></li> ");
document.writeln("           </ul> ");
document.writeln("         </li> ");
document.writeln("         <li><a target=\"_parent\"  class=\"fly\" href=\"#url\">Good Stuff</a> ");
document.writeln("           <ul> ");
document.writeln("             <li><a class=\"fly\" href=\"#url\">Work</a> <!-- 3 level, li is start,  not terminated until after end of ul --> ");
document.writeln(" 			  	<ul> ");
document.writeln("                  <li><a target=\"_parent\"   href=\"../PassChk.php\">Gary Secret</a></li> ");
document.writeln("                 <li><a target=\"_parent\"   href=\"../XXSoftwareTools/GaryTestCSSDOM.html\">Tests</a></li> ");
document.writeln("                 <li><a target=\"_parent\"   href=\"http://wpdev.garyjohnsoninfo.info/\">WP</a></li> ");
document.writeln("                 <li><a target=\"_parent\"   href=\"http://wpdev.garyjohnsoninfo.info/wp-admin/\">WP Dash</a></li> ");
document.writeln(" 			  	</ul> ");
document.writeln(" 			  </li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"http://www.youtube.com/garyjohnson53\">Our Video</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"http://picasaweb.google.com/gary.johnson.53\">Our Pictures</a></li> ");
document.writeln("             <li><a target=\"_parent\"   href=\"../XXSoftwareTools/widgets.html\">My Widgets</a></li> ");
document.writeln("           </ul> ");
document.writeln("         </li> ");
document.writeln("         <li><a target=\"_parent\"  href=\"../index.html\">Home</a></li> ");
document.writeln("         <li><a target=\"_parent\"  href=\"../oldindex.html\">Site Map</a></li> ");
document.writeln("         <li><a target=\"_parent\"  href=\"../newindex.html\">Miscellaneous</a></li> ");

document.writeln("       </ul> <!-- end of 2 level ul --> ");
document.writeln("     </li> ");
document.writeln("   </ul> <!-- end of 1 level ul --> ");
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29861433-1']);
  _gaq.push(['_setDomainName', 'garyjohnsoninfo.info']);
  _gaq.push(['_setAllowLinker', true]);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
$(document).ready(function() {
 $("#navigation").navPlugin({
   'itemWidth': 210,
   'itemHeight': 30,
   'navEffect': "slide",
   'speed': 250
 });
}); // end ready